all: main.cpp  resource.res
	x86_64-w64-mingw32-g++ -o mouse-mv.exe resource.res main.cpp -mwindows
	x86_64-w64-mingw32-strip mouse-mv.exe

resource.res: resource.rc mouse-mv.ico
	x86_64-w64-mingw32-windres -i resource.rc --input-format=rc -o resource.res -O coff
